<a href="https://colab.research.google.com/github/Ange1Bz/Practica/blob/main/Practica_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version

Python 3.10.12


In [ ]:
import numpy as np
tutorial=np.array([3,33,333])
print(tutorial)
print (tutorial.shape)

[  3  33 333]
(3,)


In [ ]:
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120


(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
c=np.random.randint(low=4,high=12,size=(2,2))
d=np.random.randint(low=4,high=8,size=(2,2))

In [ ]:
c

array([[11,  8],
       [ 9,  4]])

In [ ]:
d

array([[5, 6],
       [5, 7]])

In [ ]:
aux=np.vstack((c,d))
print(aux)

[[11  8]
 [ 9  4]
 [ 5  6]
 [ 5  7]]


In [ ]:
aux=np.hstack((c,d))
print(aux)

[[11  8  5  6]
 [ 9  4  5  7]]


In [20]:
c=np.random.randint(low=1,high=14,size=(9))
print(c)
print(c.shape)


[11  6 13 12 13 12 12 10  2]
(9,)


In [22]:
filter=(c<3)
print (c[filter])


[2]
